# Name of the openshift cluster
cluster_name: sno

# The openshift cluster's domain
cluster_domain: batchelor.live

# The openshift cluster's api
cluster_api: 'https://api.{{ cluster_name }}.{{ cluster_domain }}:6443'

gitops_catalog: 'https://github.com/JustinBatchelor/gitops-catalog'

operators_iac_repo:
  url: 'https://github.com/JustinBatchelor/homelab'
  path: 'iac/sno/config'
  name: 'iac-operators-argocd'
  namespace: 'openshift-gitops'