---
- name: Include tasks to create instances of all operators deployed 
  ansible.builtin.include_tasks: operator-instances.yaml
  
- name: Include tasks to create argocd application for LLM front-end interface
  ansible.builtin.include_tasks: openweb-ui.yaml
