apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Red Hat Single Sign-On Operator
  - github.com/JustinBatchelor/gitops-catalog//rhsso/rhsso-standalone/overlays/default/stable?ref=main
