apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # OpenShift Virtualization
  - github.com/JustinBatchelor/gitops-catalog//virtualization-operator/operator/overlays/stable?ref=main
