---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ollama-models
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-models
  template:
    metadata:
      labels:
        app: ollama-models
    spec:
      containers:
        - name: ollama-models
          image: {{ .Values.ollama.image }}
          ports:
            - containerPort: 11434
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: ollama-models
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 11434-tcp
      protocol: TCP
      port: 11434
      targetPort: 11434
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ollama-models
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  host: ollama-models.apps.sno.batchelor.live
  to:
    kind: Service
    name: ollama-models
    weight: 100
  port:
    targetPort: 11434-tcp
  tls:
    termination: edge
  wildcardPolicy: None