# Default values for ollama-llm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ollama:
  image: "quay.io/rh-aiservices-bu/ollama-ubi9@sha256:900a74cb65f26d074ba1d18cc150a69007a3893597141622a9770d0c79ec5e22"
  route: "https://ollama-models.apps.sno.batchelor.live"

open_webui:
  image: "quay.io/castawayegr/open-webui:v0.3.11"
  service_name: "open-webui"