- name: Ensure the OpenShift GitOps Operator subscription is created
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: '{{ operators_iac_repo["name"] }}'
        namespace: '{{ operators_iac_repo["namespace"] }}'
      spec:
        project: default
        source:
          repoURL: '{{ operators_iac_repo["url"] }}'
          targetRevision: HEAD
          path: '{{ operators_iac_repo["path"] }}'
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true

- name: Include tasks that validate the operator is installed and 'Available'
  ansible.builtin.include_tasks: validations/gitops.yaml
  vars:
    instance_name: '{{ operators_iac_repo["name"] }}'

